"""
categories_config.py

Contains the predefined mapping of section titles to categories
for study section classification.
"""

categories_sparse = {
        "TITLE": [
            "name of the study",
            "title",
            "full title", 
        ],
        "JUSTIFICATION": [
            "background",
            "scientific justification", 
            "rationale", 
            "main backgrounds",
        ],
        "OBJECTIVE": [
            "objectives",
            "main objective and primary endpoint",
            "main end-points",
            "primary objective",
            "primary objectives",
            "criteria of assessment",
            "primary objective and assessment criterion",
            "objective and primary endpoint", 
            "objectives and secondary endpoints", 
            "secondary objectives",
            "secondary objectives and endpoints",
            "secondary objectives and assessment criteria",
            "secondary end-points",
            "study endpoints",
            "study objectives",
            "evaluation criteria",
            "Questions asked in the CAALL-F01 protocol",
        ],
        "DESIGN": [
            "Study Design",
            "design / phase / category",
            "design of the study",
            "design of the trial",
            "experimental design",
            "diagnostic method",
            "reference diagnostic method",
            "Scope of the trial",
            "ancillary study",
            "type of study",
        ],
        "INCLUSION CRITERIA": [
            "inclusion criteria",
            "preinclusion criteria",
            "graall-2014/b inclusion criteria",
            "graall-quest inclusion criteria",
            "inclusion criteria observational phase: (n°1,2,3,4,6,7,8,9) interventional phase: (n°1,2,3,4,5,6,7,8).",
            "inclusion criteria   ",
            "inclusion criteria of donors",
            "inclusion criteria of patients",
            "population concerned",
            "population involved",
            "population of study participants",
            "population of trial subjects",
            "Indication",
        ],
        "EXCLUSION CRITERIA": [
            "graall-2014/b non inclusion criteria",
            "graall-quest non inclusion criteria",
            "non-preinclusion and non-inclusion criteria",
            "non-inclusion criteria",
            "non inclusion criteria",
            "exclusion criteria observational phase: (n°1,2,3) interventional phase: (n°:1,2,3,4,5,6,7,8).",
            "exclusion criteria",
            "exclusion criteria :",
            "exclusion criteria of patients",
            "exclusion criterion",
        ],
        "INTERVENTION" : [
            "reference treatment",
            "transplant modalities",
            "transplant modalities medical product provided by the Sponsor",
            "transplantation modalities",
            "transplants modalities",
            "treatment (transplant modalities)",
            "treatment being tested",
            "treatment",
            "benchmark treatment",
            "comparator strategy and treatment",
            "comparator treatment",
            "concomitant treatments",
            "experimental treatment",
            "experimental drug prescription outside ma",
            "experimental drugs prescription according to ma",
            "experimental group",
            "investigational medicinal product(s)",
            "investigational drug",
            "investigational medicinal product",
            "medicinal product and auxiliairy medicinal products",
            "investigational medicinal products",
            "investigational strategy and medicinal product(s)",
            "investigational medicinal product and auxiliairy medicinal products",
            "Study Intervention",
            "Study intervention",
            "chemotherapy",
            "Challenge agents",
            "comparator",
            "comparator arm",
        ],
        "STATISTICS": [
            "statistical justification of sample size",
            "statistical analysis",
            "statistical power and sample size justification:",
            "first interim analysis",
            "sample size",
        ]
    }


categories_exact = {
        "TITLE": [
            "name of the study",
            "title",
            "full title", 
        ],
        "JUSTIFICATION": [
            "background",
            "scientific justification", 
            "rationale", 
            "main backgrounds",
        ],
        "OBJECTIVE": [
            "objectives",
            "main objective and primary endpoint",
            "main end-points",
            "primary objective",
            "primary objectives",
            "criteria of assessment",
            "primary objective and assessment criterion",
            "objective and primary endpoint", 
            "objectives and secondary endpoints", 
            "secondary objectives",
            "secondary objectives and endpoints",
            "secondary objectives and assessment criteria",
            "secondary end-points",
            "study endpoints",
            "study objectives",
            "evaluation criteria",
            "questions asked in the caall-f01 protocol",
        ],
        "DESIGN": [
            "study design",
            "design / phase / category",
            "design of the study",
            "design of the trial",
            "experimental design",
            "diagnostic method",
            "reference diagnostic method",
            "scope of the trial",
            "ancillary study",
            "type of study",
        ],
        "INCLUSION CRITERIA": [
            "inclusion criteria",
            "preinclusion criteria",
            "graall-2014/b inclusion criteria",
            "graall-quest inclusion criteria",
            "inclusion criteria observational phase: (n°1,2,3,4,6,7,8,9) interventional phase: (n°1,2,3,4,5,6,7,8).",
            "inclusion criteria   ",
            "inclusion criteria of donors",
            "inclusion criteria of patients",
            "population concerned",
            "population involved",
            "population of study participants",
            "population of trial subjects",
            "indication",
        ],
        "EXCLUSION CRITERIA": [
            "graall-2014/b non inclusion criteria",
            "graall-quest non inclusion criteria",
            "non-preinclusion and non-inclusion criteria",
            "non-inclusion criteria",
            "non inclusion criteria",
            "exclusion criteria observational phase: (n°1,2,3) interventional phase: (n°:1,2,3,4,5,6,7,8).",
            "exclusion criteria",
            "exclusion criteria :",
            "exclusion criteria of patients",
            "exclusion criterion",
        ],
        "INTERVENTION" : [
            "reference treatment",
            "transplant modalities",
            "transplant modalities medical product provided by the sponsor",
            "transplantation modalities",
            "transplants modalities",
            "treatment (transplant modalities)",
            "treatment being tested",
            "treatment",
            "benchmark treatment",
            "comparator strategy and treatment",
            "comparator treatment",
            "concomitant treatments",
            "experimental treatment",
            "experimental drug prescription outside ma",
            "experimental drugs prescription according to ma",
            "experimental group",
            "investigational medicinal product(s)",
            "investigational drug",
            "investigational medicinal product",
            "medicinal product and auxiliairy medicinal products",
            "investigational medicinal products",
            "investigational strategy and medicinal product(s)",
            "investigational medicinal product and auxiliairy medicinal products",
            "study intervention",
            "chemotherapy",
            "challenge agents",
            "comparator",
            "comparator arm",
        ],
        "STATISTICS": [
            "statistical justification of sample size",
            "statistical analysis",
            "statistical power and sample size justification:",
            "first interim analysis",
            "sample size",
        ],
        "DSMB" : [
            "dsmb",
            "dsmb (data safety monitoring board)",
            "dsmb : data safety monitoring board",
            "data safety monitoring board",
            "data safety monitoring board anticipated",
            "independent surveillance committee planned",
            "study will have a data safety monitoring board",
            "trial will have a data monitoring committee",
            "trial will have a data safety monitoring board",
        ],
        "ACRONYM" : [
            "abbreviated title",
            "acronym",
            "acronym/reference",
            "short title",
            "study acronym",
            "clinical trial code",
        ],
        "INVESTIGATOR" : [
            "coordinating investigator",
            "coordinating investigator and scientific director",
            "coordinating investigator and scientific director",
            "coordinating investigators",
            "coordinator",
            "scientific director",
            "scientific director (if applicable)"
        ],
        "NUMBER OF INCLUSIONS": [
            "number of participants included",
            "number of participants chosen",
            "number of selected subjects",
            "number of subjects chosen",
            "number of subjects included",
            "number of subjects required",
        ],
        "SITES" : [
            "number of valued sites",
            "clinical sites",
            "centres: 28",
            "number of sites",
            "number of centers",
            "number of centres",
        ],
        "FUNDING": [
            "study sponsor",
            "sources of funding for the trial",
            "sources of monetary support",
            "sponsor",
            "financing",
            "funding",
            "funding source",
            "funding sources",
            "budget",
        ],
    }